### ISSUE TITLE
EGL2 closes 5 seconds after starting.

### ISSUE THREAD

**Issue by SimonBData** [WorkingRobot/EGL2#19]

**Comment by SimonBData** [comment]
winfsp-1.7.20038 loaded correctly

**Comment by Bevan0** [comment]
Hey, can you post a log file? You'll find them in %appdata%/EGL2/logs (enter that in the top bar of file explorer)

**Comment by SimonBData** [comment]
There are 39 of them, should I attach them all?

**Comment by Bevan0** [comment]
Attach whatever one is most recent.

**Comment by Bevan0** [comment]
If you can't work that out, then you can attach them all.

**Comment by SimonBData** [comment]
I guess that's what you need
[2020-06-17_10-45-33.log](https://github.com/WorkingRobot/EGL2/files/4791088/2020-06-17_10-45-33.log)
